# Generated by Django 4.2.3 on 2023-07-21 23:28

import Apis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8)),
                ('paxx', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_habitacion', models.PositiveIntegerField(unique=True)),
                ('nro_piso', models.PositiveSmallIntegerField()),
                ('tipo_habitacion', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Reservado', 'Reservado'), ('Limpieza', 'Limpieza'), ('No operativo', 'NoOperativo')], default='Libre', max_length=12)),
                ('tamanio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagen', models.ImageField(null=True, upload_to='habitaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino')], max_length=9)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=30)),
                ('telefono', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruc_empresa', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('rol', models.CharField(choices=[('recepcionista', 'recepcionista'), ('gerente', 'gerente')], default='recepcionista', max_length=15)),
                ('turno', models.CharField(choices=[('mañana', 'mañana'), ('tarde', 'tarde'), ('noche', 'noche'), ('finesSemana', 'finesSemana')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
            managers=[
                ('objects', Apis.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dias', models.PositiveIntegerField()),
                ('tipo_reserva', models.CharField(choices=[('Presencial', 'presencial'), ('Virtual', 'virtual')], default='presencial', max_length=15)),
                ('razon_hospedaje', models.CharField(max_length=50)),
                ('peticiones', models.TextField(max_length=100)),
                ('fecha_llegada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'pendiente'), ('Cancelado', 'cancelado'), ('Pasado', 'pasado'), ('Registrado', 'Registrado')], default='Pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.habitacion')),
                ('recepcionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('descripcion_salida', models.CharField(blank=True, max_length=500, null=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apis.checkin')),
                ('recepcionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='recepcionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apis.reserva'),
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino')], max_length=9)),
                ('tipo_identificacion', models.CharField(max_length=20, null=True)),
                ('identificacion', models.CharField(max_length=20, null=True, unique=True)),
                ('relacion', models.CharField(help_text='Relación con el titular', max_length=50)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.huesped')),
            ],
        ),
    ]
