# Generated by Django 4.2.3 on 2023-07-21 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino')], max_length=9)),
                ('tipo_identificacion', models.CharField(max_length=20, null=True)),
                ('identificacion', models.CharField(max_length=20, null=True, unique=True)),
                ('relacion', models.CharField(help_text='Relación con el titular', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'activo'), ('Inactivo', 'inactivo')], default='Activo', max_length=8)),
                ('paxx', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('descripcion_salida', models.CharField(blank=True, max_length=500, null=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apis.checkin')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_habitacion', models.PositiveIntegerField(unique=True)),
                ('nro_piso', models.PositiveSmallIntegerField()),
                ('tipo_habitacion', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Reservado', 'Reservado'), ('Limpieza', 'Limpieza'), ('No operativo', 'NoOperativo')], default='Libre', max_length=12)),
                ('tamanio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagen', models.ImageField(upload_to='habitaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino')], max_length=9)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=30)),
                ('telefono', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruc_empresa', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dias', models.PositiveIntegerField()),
                ('tipo_reserva', models.CharField(choices=[('Presencial', 'presencial'), ('Virtual', 'virtual')], default='presencial', max_length=15)),
                ('razon_hospedaje', models.CharField(max_length=50)),
                ('peticiones', models.TextField(max_length=100)),
                ('fecha_llegada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'pendiente'), ('Cancelado', 'cancelado'), ('Pasado', 'pasado'), ('Registrado', 'Registrado')], default='Pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.habitacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_recepcionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.huesped'),
        ),
        migrations.AddField(
            model_name='detallecontenido',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.habitacion'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='id_recepcionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='id_recepcionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apis.reserva'),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.huesped'),
        ),
    ]
