# Generated by Django 4.2.3 on 2023-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_alter_huesped_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Dni', 'Dni'), ('Carnet_Extranjeria', 'Carnet_Extranjeria')], max_length=20),
        ),
    ]
