# Generated by Django 4.2.3 on 2023-07-21 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_acompanante_checkin_checkout_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contenido',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='habitacion',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Apis.habitacion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetalleContenido',
        ),
    ]
