# Generated by Django 4.2.3 on 2023-07-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_contenido_cantidad_contenido_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='id_recepcionista',
            new_name='recepcionista',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='id_recepcionista',
            new_name='recepcionista',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_recepcionista',
            new_name='recepcionista',
        ),
    ]
