# Generated by Django 4.2.3 on 2023-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0005_acompanante_created_at_acompanante_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_llegada',
            field=models.DateField(),
        ),
    ]
