# Generated by Django 4.2.3 on 2023-07-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0005_rename_id_recepcionista_checkin_recepcionista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='Habitacion',
            new_name='habitacion',
        ),
    ]
