# Generated by Django 4.2.3 on 2023-07-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0006_alter_reserva_fecha_llegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='ruc_empresa',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
