# Generated by Django 4.2.3 on 2023-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0007_alter_huesped_ruc_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='peticiones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
