# Generated by Django 4.2.3 on 2023-07-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0010_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='hospedado',
            field=models.BooleanField(default=False),
        ),
    ]
